"""phase 8: question clusters + curated docs

Revision ID: 569e060edab5
Revises: cd1494022c72
Create Date: 2026-09-06 14:17:09.586366

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = '569e060edab5'
down_revision = 'cd1494022c72'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # new DocumentType for admin-authored answers from the learning center.
    # PG12+ allows ADD VALUE inside a transaction as long as it isn't used here.
    op.execute("ALTER TYPE documenttype ADD VALUE IF NOT EXISTS 'curated'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_clusters',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('centroid', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('representative_text', sa.Text(), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('top_kb_similarity', sa.Float(), nullable=False),
    sa.Column('is_gap', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('open', 'addressed', 'dismissed', name='clusterstatus'), nullable=False),
    sa.Column('resolved_document_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['resolved_document_id'], ['knowledge_documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_clusters_is_gap'), 'question_clusters', ['is_gap'], unique=False)
    op.create_index(op.f('ix_question_clusters_organization_id'), 'question_clusters', ['organization_id'], unique=False)
    op.create_table('question_cluster_members',
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['question_clusters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_index(op.f('ix_question_cluster_members_cluster_id'), 'question_cluster_members', ['cluster_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_cluster_members_cluster_id'), table_name='question_cluster_members')
    op.drop_table('question_cluster_members')
    op.drop_index(op.f('ix_question_clusters_organization_id'), table_name='question_clusters')
    op.drop_index(op.f('ix_question_clusters_is_gap'), table_name='question_clusters')
    op.drop_table('question_clusters')
    # ### end Alembic commands ###
