"""phase 5: message intent and entities

Revision ID: cf52531e1fae
Revises: 18502e85a31b
Create Date: 2026-09-06 12:47:37.869319

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cf52531e1fae'
down_revision = '18502e85a31b'
branch_labels = None
depends_on = None


messageintent = postgresql.ENUM(
    'billing', 'technical_support', 'account_management', 'complaint',
    'sales_inquiry', 'general_inquiry', 'other', 'unknown',
    name='messageintent',
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column does not auto-CREATE the enum type (unlike create_table) — do it here.
    messageintent.create(op.get_bind(), checkfirst=True)
    op.add_column('messages', sa.Column('intent', messageintent, nullable=True))
    op.add_column('messages', sa.Column('intent_confidence', sa.Float(), nullable=True))
    # server_default so the NOT NULL add succeeds on rows that already exist;
    # the ORM sets `entities` explicitly on every insert, so drop the DB default
    # again to keep the source of truth in Python.
    op.add_column(
        'messages',
        sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), nullable=False,
                  server_default=sa.text("'{}'::jsonb")),
    )
    op.alter_column('messages', 'entities', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'entities')
    op.drop_column('messages', 'intent_confidence')
    op.drop_column('messages', 'intent')
    messageintent.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
